#
# This file has been generated by tools/gen-deps.sh
#

src/justc-forstdin/justc-forstdin.o src/justc-forstdin/justc-forstdin.lo: src/justc-forstdin/justc-forstdin.c

justc-forstdin: EXTRA_LIBS :=
justc-forstdin: src/justc-forstdin/justc-forstdin.o -lexecline -lskarnet
